"""initial schema

Revision ID: 86f40f08d80a
Revises: 
Create Date: 2026-09-03 12:10:38.553211
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial_schema'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('phase', sa.String(length=16), nullable=True),
    sa.Column('input_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_via', sa.String(length=16), nullable=True),
    sa.Column('feedback_rating', sa.String(length=16), nullable=True),
    sa.Column('feedback_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_briefs'))
    )
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_briefs_date'), ['date'], unique=False)

    op.create_table('days',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_days'))
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('push_token', name=op.f('uq_devices_push_token'))
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('intervention', sa.Text(), nullable=False),
    sa.Column('baseline_start', sa.Date(), nullable=True),
    sa.Column('baseline_end', sa.Date(), nullable=True),
    sa.Column('intervention_start', sa.Date(), nullable=True),
    sa.Column('intervention_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('confidence_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('supporting_metric', sa.String(length=64), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('strength', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights'))
    )
    op.create_table('oauth_tokens',
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider', name=op.f('pk_oauth_tokens'))
    )
    op.create_table('raw_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=False),
    sa.Column('record_type', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_records')),
    sa.UniqueConstraint('source', 'source_record_id', name=op.f('uq_raw_records_source'))
    )
    with op.batch_alter_table('raw_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_records_record_type'), ['record_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_records_source'), ['source'], unique=False)

    op.create_table('supplements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dose_amount', sa.Float(), nullable=True),
    sa.Column('dose_unit', sa.String(length=24), nullable=True),
    sa.Column('form', sa.String(length=32), nullable=True),
    sa.Column('schedule', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplements')),
    sa.UniqueConstraint('name', name=op.f('uq_supplements_name'))
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records_ingested', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_source'), ['source'], unique=False)

    op.create_table('activity_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('active_energy_kcal', sa.Float(), nullable=True),
    sa.Column('total_energy_kcal', sa.Float(), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['days.date'], name=op.f('fk_activity_daily_date_days')),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_activity_daily'))
    )
    op.create_table('body_measurements',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Float(), nullable=True),
    sa.Column('bone_mass_kg', sa.Float(), nullable=True),
    sa.Column('water_pct', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('arm_cm', sa.Float(), nullable=True),
    sa.Column('thigh_cm', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['days.date'], name=op.f('fk_body_measurements_date_days')),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_body_measurements'))
    )
    op.create_table('checkins',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_late', sa.Boolean(), nullable=False),
    sa.Column('energy_1_5', sa.Integer(), nullable=True),
    sa.Column('mood_1_5', sa.Integer(), nullable=True),
    sa.Column('sleep_quality_1_5', sa.Integer(), nullable=True),
    sa.Column('soreness_1_5', sa.Integer(), nullable=True),
    sa.Column('motivation_1_5', sa.Integer(), nullable=True),
    sa.Column('focus_1_5', sa.Integer(), nullable=True),
    sa.Column('stress_1_5', sa.Integer(), nullable=True),
    sa.Column('overall_1_10', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['days.date'], name=op.f('fk_checkins_date_days')),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_checkins'))
    )
    op.create_table('daily_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('readiness_components', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('readiness_confidence', sa.String(length=16), nullable=True),
    sa.Column('sleep_debt_14d_min', sa.Float(), nullable=True),
    sa.Column('sleep_midpoint_variance_min', sa.Float(), nullable=True),
    sa.Column('rhr_deviation_bpm', sa.Float(), nullable=True),
    sa.Column('hrv_deviation_pct', sa.Float(), nullable=True),
    sa.Column('acute_load_7d', sa.Float(), nullable=True),
    sa.Column('chronic_load_28d', sa.Float(), nullable=True),
    sa.Column('acwr', sa.Float(), nullable=True),
    sa.Column('weight_ewma_kg', sa.Float(), nullable=True),
    sa.Column('weight_trend_kg_per_week', sa.Float(), nullable=True),
    sa.Column('protein_g_per_kg', sa.Float(), nullable=True),
    sa.Column('data_completeness_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['days.date'], name=op.f('fk_daily_metrics_date_days')),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_daily_metrics'))
    )
    op.create_table('heart_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('resting_hr', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('hrv_rmssd_ms', sa.Float(), nullable=True),
    sa.Column('vo2max', sa.Float(), nullable=True),
    sa.Column('stress_avg', sa.Float(), nullable=True),
    sa.Column('energy_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['days.date'], name=op.f('fk_heart_metrics_date_days')),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_heart_metrics'))
    )
    op.create_table('nutrition_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calories_kcal', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('fibre_g', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('water_ml', sa.Float(), nullable=True),
    sa.Column('alcohol_units', sa.Float(), nullable=True),
    sa.Column('caffeine_mg', sa.Float(), nullable=True),
    sa.Column('last_caffeine_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_meal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('completeness_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['days.date'], name=op.f('fk_nutrition_daily_date_days')),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_nutrition_daily'))
    )
    op.create_table('protocol_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entity_type', sa.String(length=24), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(length=24), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_protocol_changes_experiment_id_experiments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_protocol_changes'))
    )
    op.create_table('sleep_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('time_in_bed_min', sa.Integer(), nullable=True),
    sa.Column('efficiency_pct', sa.Float(), nullable=True),
    sa.Column('deep_min', sa.Integer(), nullable=True),
    sa.Column('rem_min', sa.Integer(), nullable=True),
    sa.Column('light_min', sa.Integer(), nullable=True),
    sa.Column('awake_min', sa.Integer(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('min_hr', sa.Float(), nullable=True),
    sa.Column('avg_hrv_ms', sa.Float(), nullable=True),
    sa.Column('avg_spo2', sa.Float(), nullable=True),
    sa.Column('respiratory_rate', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['date'], ['days.date'], name=op.f('fk_sleep_sessions_date_days')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sleep_sessions'))
    )
    with op.batch_alter_table('sleep_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sleep_sessions_date'), ['date'], unique=False)

    op.create_table('supplement_log',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('supplement_id', sa.Integer(), nullable=False),
    sa.Column('taken', sa.Boolean(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dose_override', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['days.date'], name=op.f('fk_supplement_log_date_days')),
    sa.ForeignKeyConstraint(['supplement_id'], ['supplements.id'], name=op.f('fk_supplement_log_supplement_id_supplements')),
    sa.PrimaryKeyConstraint('date', 'supplement_id', name=op.f('pk_supplement_log'))
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('perceived_exertion_1_10', sa.Float(), nullable=True),
    sa.Column('total_volume_kg', sa.Float(), nullable=True),
    sa.Column('set_count', sa.Integer(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Float(), nullable=True),
    sa.Column('energy_kcal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['days.date'], name=op.f('fk_workouts_date_days')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workouts')),
    sa.UniqueConstraint('source', 'source_record_id', name=op.f('uq_workouts_source'))
    )
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workouts_date'), ['date'], unique=False)

    op.create_table('workout_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('exercise_template_id', sa.String(length=128), nullable=True),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.String(length=24), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('is_pr', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_workout_sets_workout_id_workouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_sets'))
    )
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_sets_exercise_name'), ['exercise_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sets_exercise_template_id'), ['exercise_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_sets_workout_id'), ['workout_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_sets_workout_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sets_exercise_template_id'))
        batch_op.drop_index(batch_op.f('ix_workout_sets_exercise_name'))

    op.drop_table('workout_sets')
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workouts_date'))

    op.drop_table('workouts')
    op.drop_table('supplement_log')
    with op.batch_alter_table('sleep_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_sessions_date'))

    op.drop_table('sleep_sessions')
    op.drop_table('protocol_changes')
    op.drop_table('nutrition_daily')
    op.drop_table('heart_metrics')
    op.drop_table('daily_metrics')
    op.drop_table('checkins')
    op.drop_table('body_measurements')
    op.drop_table('activity_daily')
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_runs_source'))

    op.drop_table('sync_runs')
    op.drop_table('supplements')
    with op.batch_alter_table('raw_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_records_source'))
        batch_op.drop_index(batch_op.f('ix_raw_records_record_type'))

    op.drop_table('raw_records')
    op.drop_table('oauth_tokens')
    op.drop_table('insights')
    op.drop_table('experiments')
    op.drop_table('devices')
    op.drop_table('days')
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_briefs_date'))

    op.drop_table('briefs')
    # ### end Alembic commands ###
